/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/cos-theme.ts
 * Command: astryx theme build theme/cos-theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./cos.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const cosTheme: DefinedTheme;
