/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/cos-theme.ts
 * Command: astryx theme build theme/cos-theme.ts
 * Generated: 2026-07-30T01:06:09.011Z
 */

/// <reference path="./cos.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const cosTheme: DefinedTheme;
