/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/cos-theme.ts
 * Command: astryx theme build theme/cos-theme.ts
 * Generated: 2026-07-30T01:06:09.010Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
